PHASE_TIME_PLOT_WIDTH = 128
PHASE_TIME_PLOT_HEIGHT = 64

PHASE_BAND_PLOT_WIDTH = 128
PHASE_BAND_PLOT_HEIGHT = 128

TIME_PLOT_LENGTH = 256

CHI_VS_DM_PLOT_LENGTH = 1000

CLASS_ID_TO_LABEL = {
    0: 'not pulsar',
    1: 'pulsar',
}

CLASS_LABEL_TO_ID = {v: k for k, v in CLASS_ID_TO_LABEL.items()}

BATCH_SIZE = 20
